name: UClans
main: me.ulrich.clans.Clans
version: 3.0.6
author: UlrichBR
website: https://www.spigotmc.org/resources/authors/543977/
description: The best and most complete system of clans and lands.
api-version: 1.13
softdepend: [UChestClan, Vault, PlaceholderAPI, PrototolLib, SuperVanish, PremiumVanish, WorldGuard, WorldEdit]
commands:
   uclan:
      description: Open the help staff menu.
      usage: /<command>
      aliases: [uclans, uc, ugang, ug, uteam]
   clan:
      description: Open the help player menu.
      usage: /<command>
      aliases: [clans, c, gang, team]
   clanchat:
      description: Use Clan chat.
      usage: /<Command> help
      aliases: [.]
permissions:
  uclans.admin.*:
    children: 
      uclans.admin.help: true
      uclans.admin.addpoints: true
      uclans.admin.setpoints: true
      uclans.admin.removepoints: true
      uclans.admin.resetplayerkdr: true
      uclans.admin.resetclankdr: true
      uclans.admin.globalff: true
      uclans.admin.delete: true
      uclans.admin.forcejoin: true
      uclans.admin.verify: true
      uclans.admin.reload: true
      uclans.admin.spawnholo: true
      uclans.admin.despawnholo: true
      uclans.admin.listholos: true
      uclans.admin.tpholo: true
      uclans.admin.reloadholos: true
      uclans.admin.wand: true
      uclans.admin.clearwand: true
      uclans.admin.expand: true
      uclans.admin.addregion: true
      uclans.admin.removeregion: true
      UClans.admin.listregions: true
      UClans.admin.listregions: true
      uclans.admin.addarena: true
      uclans.admin.removearena: true
      uclans.admin.listarenas: true
      uclans.admin.setpoint: true
      uclans.admin.togglearena: true
      uclans.admin.addkit: true
      uclans.admin.deletekit: true
      uclans.admin.listkits: true
      uclans.admin.givekit: true
      uclans.admin.chatspy: true
  uclans.player.*:
    children: 
      uclans.player.help: true
      uclans.player.war: true
      uclans.player.create: true
      uclans.player.changeleader: true
      uclans.player.desc: true
      uclans.player.disband: true
      uclans.player.leave: true
      uclans.player.invite: true
      uclans.player.join: true
      uclans.player.deny: true
      uclans.player.kick: true
      uclans.player.promote: true
      uclans.player.demote: true
      uclans.player.home: true
      uclans.player.chat: true
      uclans.player.ff: true
      uclans.player.name: true
      uclans.player.modtag: true
      uclans.player.list: true
      uclans.player.info: true
      uclans.player.profile: true
      uclans.player.rival: true
      uclans.player.rivalries: true
      uclans.player.ally: true
      uclans.player.alliances: true
      uclans.player.members: true
      uclans.player.settings: true
      uclans.player.regroup: true
      uclans.player.chest: true
      uclans.player.banner: true